lib/streamy.rb
lib/streamy/message_buses/kinesis_message_bus.rb

#Just the basics with hardcoded defaults and a partition_key I'm not fully understanding yet 😅 
Need to add something like:
```ruby
Streamy.message_bus = Streamy::MessageBuses::KinesisMessageBus.new("STREAM NAME")
```
to run it.

allow kinesis to be used directly for debugging [Delivers #Cx4kjymY]

---

streamy.gemspec

It looks like you both tried to fix the same issue and when the commits were merged the dependency was duplicated.
(Now I understand better why having the gems sorted alphabetically in the Gemfile is a "best practice") 🤔

Delete duplicated dependency

---

lib/streamy/message_buses/fluent_message_bus.rb

FluentLogger has queue, buffer and socket pool internally, so basically
we shouldn't instantiate it every time we need. Otherwise it may leads
a process to have too many opened sockets.
Merging this without waiting for a review because the changed lines are suspicious of Errno::EMFILE in our production system.
FYI @balvig

fluent_message_bus: Reuse FluentLogger

---

lib/streamy/event_stores/copy_buffered_redshift_store.rb
lib/streamy/event_stores/redshift/importer.rb
lib/streamy/message_buses/fluent_message_bus.rb

Need this so that we can split the imports into smaller chunks:
Going to move ahead with this in spike mode, as I think maybe we can remove the need for all this redshift/S3 interaction if we create a consumer to handle saving the events.

Allow importer to take a file name

---

streamy.gemspec

It seems like newer version of RubyGems or Bundler now require a gemspec
to have a valid HTTP URI in its `homepage` value, as I got this error:
The gemspec at [..] is not valid. Please fix this gemspec.  The
validation error was '"TODO: Put your gem's website or public repo
URL here." is not a valid HTTP URI'

Fix broken gemspec

---

lib/streamy/message_buses/rabbit_message_bus.rb

So that when we load the rails app, e.g. console or tests, it won't try to connect to Hutch.
`Hutch.connect` could be ran multiple times, it will only [establish the connection once](https://github.com/gocardless/hutch/blob/601f1882a61c1e384fa750c418275a902659ece7/lib/hutch.rb#L46).

Move the hutch connection out of message bus initializer

---

lib/streamy/railties/consumer.rake

Instead of depending on an external `config/rabbitmq.yml` configuration file, now the consumer task will expect the rabbitmq uri to be defined in `secrets.yml`. This makes easy to have different URIs by environment

Configure rabbitmq URI in secrets.yml

---

lib/streamy.rb
lib/streamy/errors/publication_failed_error.rb
lib/streamy/message_buses/rabbit_message_bus.rb
lib/streamy/message_buses/rabbit_message_bus/message.rb
test/rabbit_message_bus_test.rb

For now we want to leave it up to each publisher how to react if the app should fail to connect to the RabbitMQ broker.
We do this by raising a custom `Streamy::PublicationFailedError` that can then be rescued in the app publishing the event, for example:
```ruby
module Events
class ApplicationEvent < Streamy::Event
def publish
super
rescue Streamy::PublicationFailedError => e
end
end
end
```
We aren't completely sure what the best way of handling this (rare) occurrence is with regards to ordering etc, but since `global-reports` doesn't care about the order of events, for now logging might be enough as we continue to get a better understanding of what the best practices are!

raise a streamy error when rabbit fails to connect

---

lib/streamy/consumer.rb
lib/streamy/railties/consumer.rake

We want to add some custom classes for error acknowledgment. In order to do that we directly call Hutch::CLI class instead of spawning a new process. Before that, we configure Hutch properly.

[Bristol Camp] Configure :error_acknodlegments  in the rake task

---

lib/streamy.rb
lib/streamy/event.rb
lib/streamy/message_buses/message_bus.rb
lib/streamy/message_buses/rabbit_message_bus.rb
lib/streamy/message_buses/rabbit_message_bus/message.rb
lib/streamy/message_buses/test_message_bus.rb
test/message_bus_test.rb
test/rabbit_message_bus_test.rb

- Have all message buses inherit from a base class to give the `Streamy::PublicationError` capability to _all_ buses, not just Rabiit
- Avoids having to actually try to connect to rabbitmq during the failure test
- Helps https://github.com/cookpad/global-web/pull/7211/commits/15f554c56444dc7755a4049cc5f0ac91b10452c3 in simulating a publication feature

refactor to help testing in other apps

---

lib/streamy/rabbit_mq/acknowledgements/abort_on_all_failures.rb

```
2018-03-18T16:15:53Z 61387 INFO -- hutch booted with pid 61387
2018-03-18T16:15:53Z 61387 INFO -- found rails project (.), booting app in development environment
2018-03-18T16:15:53Z 61387 INFO -- connecting to rabbitmq (amqp://lgfviuok@sidewinder.rmq.cloudamqp.com:5672/lgfviuok)
2018-03-18T16:15:55Z 61387 INFO -- connected to RabbitMQ at sidewinder.rmq.cloudamqp.com as lgfviuok
2018-03-18T16:15:55Z 61387 INFO -- opening rabbitmq channel with pool size 1, abort on exception false
2018-03-18T16:15:56Z 61387 INFO -- using topic exchange 'hutch'
2018-03-18T16:15:56Z 61387 INFO -- HTTP API use is disabled
2018-03-18T16:15:56Z 61387 INFO -- tracing is disabled
2018-03-18T16:15:56Z 61387 INFO -- setting up queues
2018-03-18T16:15:56Z 61387 INFO -- setting up queue: global_reports_consumer …
```

provide more information when aborting consumer

---

README.md
lib/streamy/consumer.rb
test/consumer_test.rb

This avoids the problem when the inherited consumer tries to specify its own topic but ended up consuming Streamy's default topic as every subsequent `consume` call will join topics together.
https://github.com/gocardless/hutch/blob/bc367cb/lib/hutch/consumer.rb#L30-L32

Remove default consumption topic from consumer

---

lib/streamy/consumer.rb

This helper can be placed on top of the file to pause the consumer from consuming the event on the queue. The queue and the routing of the message will still be created as if this is a live consumer.
Usage:
class SomeConsumer
include Streamy::Consumer
pause_consumer!
end

Add `pause_consumer!` helper

---

lib/streamy/railties/consumer.rake

Gives us some nice extra output for development:
```
2018-04-19T02:21:20Z 38604 INFO -- setting up queues
2018-04-19T02:21:20Z 38604 INFO -- setting up queue: global_reports_consumer_replay
2018-04-19T02:21:20Z 38604 DEBUG -- creating binding global_reports_consumer_replay <--> replay.global.#
2018-04-19T02:21:20Z 38604 INFO -- setting up paused queue: global_reports_consumer
2018-04-19T02:21:20Z 38604 DEBUG -- creating binding global_reports_consumer <--> global.#
```

Allow Rails to control worker log level

---

lib/streamy.rb
lib/streamy/consumer.rb
lib/streamy/message_buses/rabbit_message_bus/message.rb

Inspired by https://github.com/cookpad/streamy/pull/29
Needs cleaning up, but allows us to do:
```ruby
class GlobalReportsConsumer
include Streamy::Consumer
replay "global.#"
end
```
once done can switch to
```ruby
class GlobalReportsConsumer
include Streamy::Consumer
consume "global.#"
end
```
(but also need to "manually" avoid duplication with timestamp or something)
It will set up two queues, the "replay" queue binding to `replay.global_reports_consumer.global.#` (from which it will consume) and the "realtime" queue (from which I'm _hoping_ it won't consume 😅 now testing).

Slightly different approach to 'replay mode'

---

lib/streamy.rb
lib/streamy/message_buses/rabbit_message_bus.rb
lib/streamy/message_buses/rabbit_message_bus/message.rb
test/rabbit_message_bus_test.rb

`routing_key` is a RabbitMQ-specific feature, so this PR moves it into the `RabbitMessageBus`

Treat routing key prefix as RabbitMQ-specific feature

---

lib/streamy/event.rb
test/event_test.rb

Got confused by:
```
RuntimeError:
event_time not implemented on event
```
when I accidentally removed `event_time` in an event 😅 
This PR tries to make it a little bit more obvious what is going by tweaking the error message.

Add better error messages for missing event methods

---

lib/streamy/message_buses/rabbit_message_bus.rb
lib/streamy/message_buses/rabbit_message_bus/message.rb
test/rabbit_message_bus_test.rb

In actual usage, I find the fact that messages get their routing key prefixed with `global` more confusing than helpful 😅 
Probably better to leave this control to individual event producers, to set it as part of their `topic`.
Ie
```rb
def topic
"global-web.bookmarks"
end
```
for example.
Then consumers can specify what events they are interested in and where they come from.
```rb
consume "global-web.bookmarks.#"
consume "#"
consume "global-newsletters.something.#"
```
We however still need the feature of being able to configure the routing key for _replays_, so keeping that.

Don't set prefix by default

---

README.md
lib/streamy/consumer.rb
test/consumer_test.rb

Will need this when switching from `replay` to avoid events already replayed also being consumed as realtime events once we switch out of replay mode and catch up with the realtime queue.

Revive timestamp filtering capability

---

lib/streamy/message_buses/kafka_message_bus.rb
test/message_buses/kafka_message_bus_test.rb

Fixes a bug where we were trying to send a hash instead of a json payload.

Change Kafka payload to JSON

---

lib/streamy/message_buses/kafka_message_bus.rb
streamy.gemspec
test/message_buses/kafka_message_bus_test.rb

Rather than inject the Kafka dependency into the KafkaMessageBus, this PR allows passing just the configuration for Kafka in.

Allow Streamy to configure Kafka message bus directly

---

lib/streamy/helpers/rspec_helper.rb

Small change to allow us to also test message key in RSpec helper, alongside other attributes.

Support testing message key in RSpec

---

lib/streamy/helpers/rspec_helper.rb
lib/streamy/helpers/test_unit_helper.rb

Closes https://github.com/cookpad/streamy/issues/47
Allows `body` to be left out of assertions, and shortens the helper name.

allow fuzzier assertions

---

lib/streamy/message_buses/kafka_message_bus.rb

This is not required, and indeed can be a little missleading.
* Even if there are no producers (becuase no messages were sent) we still
log.
* If there were some errors shutting down the consumer we still see:
> Kafka producers shutdown successfully👌
* The logging that ruby-kafka does is OK... e.g. messages like:
> Failed to deliver messages during shutdown: Could not connect to any of the seed brokers:
> - kafka://localhost:9092: Connection refused - connect(2) for [::1]:9092

Remove logging around Kafka producer shutdown

---

lib/streamy/event_handler.rb
test/event_handler_test.rb

In preparation for hooking up global-reports to the kafka stream, am working on extracting some of the conventions to Streamy and consolidating them with some of the original ideas.
This takes some of what's found in https://github.com/cookpad/global-feeds/blob/master/app/handlers/application_handler.rb and adds it to the streamy `EventHandler`.

Consolidate global-reports / global-feed conventions

---

lib/streamy/helpers/assert_event.rb
lib/streamy/helpers/minitest_helper.rb
test/event_test.rb
test/streamy_test.rb
test/test_helper.rb

Noticed over in https://github.com/cookpad/streamy/pull/62 some copy/pasta that we can avoid, and that we weren't making use of the built-in `assert_published_event` helper Streamy already provides.
Going to go ahead and merge this in the interest of expediency, so can better submit some suggestions in the other PR 🙇

Refactor tests

---

lib/streamy/helpers/message_parser.rb
lib/streamy/helpers/rspec_helper.rb
lib/streamy/version.rb

This PR updates the spec helper for rspec, allowing avro events to be tested, plus a bit of refactoring. It also includes the version bumped to `0.3.1`.
I have added a Kaizen issue for the updating of the spec helpers for minitest as discussed here https://github.com/cookpad/streamy/pull/62#pullrequestreview-223660846.

Update spec helpers for events

---

lib/streamy/helpers/rspec_helper.rb
lib/streamy/version.rb

This PR just updates the rspec avro helper to ensure that we have the correct value/format for time when we encode with avro.

Update rspec avro helper

---

lib/streamy/avro_event.rb
test/test_helper.rb

Tests shouldn't print anything to STDOUT. This does just add unnecessary noise to the output.
```
~/Projects/streamy (cb/silence_test_log_output) > bundle exec rake test
Run options: --seed 25526
..........................
Finished in 0.021245s, 1223.8174 runs/s, 2071.0755 assertions/s.
26 runs, 44 assertions, 0 failures, 0 errors, 0 skips
```
```
~/Projects/streamy (master) > bundle exec rake test
Run options: --seed 40570
......2019-04-12 15:49:47 - Delivering 1000 batched events now
.2019-04-12 15:49:47 - Delivering 1000 batched events now
......I, [2019-04-12T15:49:47.950018 #94705]  INFO -- : Registered schema for subject `test_event`; id = 0
.I, [2019-04-12T15:49:47.952583 #94705]  INFO -- : Registered schema for subject `incorrect_attribute_event`; id = 0
............
Finished in …
```

Silence test log output

---

README.md
lib/streamy/event.rb
lib/streamy/message_buses/kafka_message_bus.rb
lib/streamy/message_buses/test_message_bus.rb
test/event_test.rb
test/message_buses/kafka_message_bus_test.rb

It is now possible to manually send batch events by calling publish in a block. When exiting the block, all published events get send to the message bus.
```ruby
ReceivedPayment.deliver do |event|
2.times each do |i|
event.publish(i)
end
end
```

Implement a manual delivery of batched events

---

lib/streamy/kafka_configuration.rb
lib/streamy/version.rb
test/message_buses/kafka_message_bus_test.rb

With all the new events that are being produced and the increase in existing events (more users) we keep reaching our max queue size as we are producing events at a faster rate than the producer can publish them to kafka. ([See explanation here](https://github.com/zendesk/ruby-kafka/blob/0f29b7605bdfc58808b880163acd5dc18ec7e409/lib/kafka/async_producer.rb#L33-L42))
We have mitigated that by setting some of our low-priority events to `:low` which means they will now be batch sent (500 at a time or every 10s whichever comes first).  I have also upped the `max_buffer_size` for the producing thread and the `max_queue_size` for the background thread in this PR. 
As a side note the standard java implementation of kafka sets the default `max_buffer_size` in bytes to `33554432` bytes which based …

Update message queue size

---

lib/streamy/message_buses/test_message_bus.rb
test/event_test.rb

In https://github.com/cookpad/streamy/pull/74 we refactored
test message bus to handle delivering of messages based on the
priority. This changes made the test message bus flaky
so we're reverting it and also it did not make much sense to
implement functionality in a test helper for this use case.

Revert changes of test message bus

---

lib/streamy.rb
lib/streamy/avro_event.rb
lib/streamy/version.rb
test/fixtures/schemas/incorrect_attribute_event.avsc
test/fixtures/schemas/test_event.avsc

Closes https://github.com/cookpad/streamy/issues/81 - This PR fixes the performance related issues we were seeing, whereby the avro schema registry was being called every time an event was published. It should only be calling the registry the first time it publishes a new schema, or on app boot for each schema type. It should then be caching the schema locally. 
It also became apparent that namespaces are required on the body record of each event, as records can not have the same name. To that end the body for each avro event will be name-spaced using the event name. 
Once this has been merged I will update the existing avro events with the correct namespaces

Fix caching for schema registry

---

lib/streamy.rb
lib/streamy/avro_event.rb
lib/streamy/event.rb
lib/streamy/helpers/rspec_helper.rb
lib/streamy/json_event.rb
lib/streamy/message_buses/kafka_message_bus.rb
lib/streamy/message_buses/message_bus.rb
lib/streamy/message_buses/test_message_bus.rb
lib/streamy/serializers/avro_serializer.rb
lib/streamy/serializers/json_serializer.rb
lib/streamy/version.rb
test/avro_event_test.rb
test/event_test.rb
test/json_event_test.rb
test/message_buses/kafka_message_bus_test.rb
test/test_helper.rb

Closes https://github.com/cookpad/streamy/issues/70 - This PR is a refactor of the way we encode our messages in both `avro` and `json`. I feel it's a nicer/cleaner way of encoding the messages. It also helps us test events more effectively. We don't need to test the types of encoding in the main rails app. (That is already tested in the encoding libraries.)
This allows us to go back to the familiar `expect_event` syntax of old. The rails app should not care about the encoding of the message, only that the event was published to the event bus.
This is actually blocking me from enabling more avro events, so would be great to get this merged asap.

[BLOCKING] Test helper refactoring

---

lib/streamy.rb
lib/streamy/avro_event.rb
lib/streamy/json_event.rb
lib/streamy/serializers/avro_serializer.rb
lib/streamy/serializers/json_serializer.rb

Partially addresses point raised by @sebasoga in https://github.com/cookpad/streamy/pull/82#discussion_r281261212:
> the original idea was to keep Streamy message-bus/format agnostic as much as possible 
I agree that the avro related code feels out of place on the `Streamy` module. Imagine that we added another type of serialization, the top-most module could quickly become a junk drawer of different serialization-related methods?
Moving it inside the serializer feels a bit more intuitive to me, and could also open up possibilities of making the loading of _any_ avro classes optional, ie to be triggered by `require "serializers/avro_serializer"` instead of always coming along with requiring Streamy.

refactor avro serialization

---

streamy.gemspec

Since we want to be able to test Streamy with newer version of Rails, including Rails 6, we should only specify the minimum required version and open up the upper bound.
With this, we can says that we only support running Streamy with the stable version of Rails, but user can choose to run Streamy against edge Rails at their own risk.

Relax Active Support version so we can run on 6.0

---

lib/streamy/helpers/rspec_helper.rb

Move generic Streamy helpers from projects making use of the gem inside the gem itself.

Move rspec helpers to streamy

---

README.md
lib/streamy/configuration.rb
lib/streamy/event.rb
lib/streamy/kafka_configuration.rb
lib/streamy/message_buses/kafka_message_bus.rb
lib/streamy/message_buses/test_message_bus.rb
test/event_test.rb
test/message_buses/kafka_message_bus_test.rb

Closes cookpad/streamy#77
This PR fixes the `:batched` event publishing implementation. This was causing issues due to [this](https://github.com/zendesk/ruby-kafka/blob/93c45a8c531e8b447f1cd9127c8bc6ce8070c0e6/lib/kafka/producer.rb#L199-L202) in ruby-kafka as we would only send batched messages when the `max_buffer_size` had been reached, causing `Kafka::BufferOverflow` errors.
I have provided a setting in config now, whereby you can set a `producer_batched_message_limit`, this ensures that the messages are sent in batches of `1000` as default. This can be set in the config. 
The `producer_batched_message_limit` should always be set below `max_buffer_size` otherwise buffer overflow errors will occur.
This also means we can remove the `Event.deliver` implementation as discussed here …

Double check `batched` implementation

---

README.md

While working the streamy events I found out that there is no documentation about the test helpers which I add now.

Add documentation about test helpers

---

README.md
lib/streamy/configuration.rb
lib/streamy/kafka_configuration.rb
lib/streamy/message_buses/kafka_message_bus.rb
test/message_buses/kafka_message_bus_test.rb

This PR updates the config for `batched_message_limit` to be part of the kafka config, rather than `Streamy` config. It also updates the check for batched_messages against the current producers' buffer size to be `>=`

Updates to batched mode

---

README.md
lib/streamy/kafka_configuration.rb
lib/streamy/message_buses/kafka_message_bus.rb
test/message_buses/kafka_message_bus_test.rb

This PR updates the implementation of batch message limit, to send the batch when the buffer reaches `[:max_buffer_size] -1 `.
This implementation is better as users of Streamy will always have the correct limit for batch sending, rather than setting to individual config attributes that they could get wrong.

Update config for batched message sending implementation

---

lib/streamy/serializers/avro_serializer.rb
test/avro_deserializer_test.rb
test/avro_event_test.rb

This is the fix for the flaky spec discovered during development of #100 
Here is the summary of the situation:
- In `AvroSerializer`, we are [memoizing the instance of `AvroTurf::Messaging`](https://github.com/cookpad/streamy/blob/34531cc4ea0a070e6d59985e15c4c93032c54e60/lib/streamy/serializers/avro_serializer.rb#L7) in a class instance variable which means that the same instance would be used for any call to `AvroSerializer::encode` test suite during a run of `rake test`. 
- `AvroTurf::Messaging` [uses an in memory cache](https://github.com/dasch/avro_turf/blob/fbcfba68f5136ea4a7fc7f88c6d09dc74ad539cb/lib/avro_turf/cached_confluent_schema_registry.rb#L32) of Avro schemas to ids and would skip registering with the server if it already had the schema in memory. 
- …

Fix flaky avro serialization tests

---

lib/streamy/avro_event.rb
lib/streamy/serializers/avro_serializer.rb
test/avro_event_test.rb
test/fixtures/schemas/my_namespace/test_event_with_schema_namespace.avsc

Adding support for namespaced schemas this is the result of https://github.com/cookpad/global-web/pull/21096. This will basically allow us to organize and re-use our schemas.
```ruby
store = AvroTurf::SchemaStore.new(path: 'my/schemas')
store.load_schemas!
person = store.find('recipes', 'ingredient') # my/schemas/recipes/ingredient.avsc exists
```
https://github.com/cookpad/developer-productivity-squad/issues/203

Adding Avro namespace schema support

---

README.md

This PR updates the CI badge to point to main branch as we update default branch name to `main`.

Update CI badge to main branch

---

lib/streamy/deserializers/avro_deserializer.rb
streamy.gemspec
test/avro_deserializer_test.rb

PR changes the method to fetch the encoded payload to deserialize (in accordance with karafka interface changes).
This allows streamy to be used alongside the newest version of the karafka gem.
> - Remove params dependency on a hash in favour of PORO 
> - removes the #[] API from params  
As a result to get an encoded message we need to call `message#raw_payload` instead of `message["payload"]`, [karafka docs](https://github.com/karafka/karafka/wiki/Serialization#deserializers)
**Related to** https://github.com/cookpad/global-feeds/pull/1230
~I added ability to pass a bloc to `AvroDeserializer#initializer` to define a source of the encoded payload source. As a result, when the gem is used along with a new karafka the following is needed~
~If the block is not passed to the method, the …

add ability to use streamy with karafka v1.4+

---

lib/streamy/event.rb
lib/streamy/event_handler.rb
lib/streamy/version.rb
test/event_handler_test.rb
test/event_test.rb

Add a new event called `RecipeWithEvent` that takes in a kwarg for the initialiser so ruby 3 kwargs can be tested for the publish method.
This regression was caught by cookpads test suite for ruby 3.

Add ruby 3 support for publish method

---

lib/streamy/dispatcher.rb
lib/streamy/version.rb
test/dispatcher_test.rb

The dispatcher code inside the tests are currently mocked via the class `TestDispatcher`. 
This means the dispatcher class is never tested and the method is never invoked https://github.com/cookpad/streamy/pull/115/files#diff-a8045b788a31b9e61bd94e501d186161b1d82ce9227f23e694c5038b5da6a6dbL8
The args have been updated to kwargs and a test for dispatcher has been included.

Fix dispatcher kwargs

---

lib/streamy.rb
lib/streamy/deserializers/avro_deserializer.rb
lib/streamy/errors/unknown_priority_error.rb
lib/streamy/errors/unknown_producer_type_error.rb
lib/streamy/kafka_configuration.rb
lib/streamy/message_buses/kafka_message_bus.rb
lib/streamy/version.rb
streamy.gemspec
test/dispatcher_test.rb
test/message_buses/kafka_message_bus_test.rb

The goal of this PR is to replace the `ruby-kafka` gem with the `waterdrop` gem as the dependency for karafka, as `ruby-kafka` is being deprecated.
Both [Ruby-Kafka](https://github.com/zendesk/ruby-kafka#deprecation-notice) and Karafka v1.4  are deprecated
1. The update involves _replacing the Kafka gem dependency with the Waterdrop gem_. While Karafka is a Kafka processing framework, Waterdrop is a gem for producing messages to Kafka. So it seems to me that Waterdrop is the right dependency here, especially since we're using Waterdrop directly.
2. I decided to stick with the existing approach of creating new producer instances when an event is published synchronously. Also, new waterdrop clients are safer in terms of potential workload (one producer should be enough for up to 5k msq/s …

Replace the `ruby-kafka` gem with the `waterdrop` gem

---

lib/streamy/errors/publication_failed_error.rb
lib/streamy/message_buses/kafka_message_bus.rb
lib/streamy/version.rb

The PR improves the logged error message by adding a cause (if it exists)
before 
Streamy::PublicationFailedError:  Failed publishing event: {:key=>"visited_recipe_x",  #... } }
WaterDrop::Errors::ProduceError - WaterDrop::Errors::ProduceError
after 
Streamy::PublicationFailedError:  Failed publishing event: {:key=>"visited_recipe_x",  #... } }
WaterDrop::Errors::ProduceError - WaterDrop::Errors::ProduceError, caused by  Local: Queue full (queue_full)
adds require "waterdrop", so it should help to fix `undefined method `shutdown'`

add cause to the logged error message 

---

.github/workflows/ci.yml
lib/streamy/message_buses/kafka_message_bus.rb
streamy.gemspec
test/message_buses/kafka_message_bus_test.rb

Update producers shutdown call
Waterdrop producers respond to close instead of shutdown

Update producers shutdown call

---

lib/streamy/event_handler.rb
lib/streamy/message_buses/outbox_message_bus.rb
streamy.gemspec
test/avro_deserializer_test.rb
test/message_buses/outbox_message_bus_test.rb

A service that updates database entities, and also writes a related event to kafka can have some issues if we decide to wrap the database updates in a transaction, then some error or delay occurs when writing and event to kafka.  Especially if the event is written synchronously.
This can also cause lock conntention and increased resource useage on the database server at scale.
* https://microservices.io/patterns/data/transactional-outbox.html
* https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/transactional-outbox.html
One solution is to write the event stream to a dedicated database table, and have an additonal process to handle writing the events to kafka.
This means that the application doesn't need to manage it's own connections to kafka, and transactions …

Add a message bus for transactional outbox deliveries
